- id: '1636588075565'
  alias: Purge the Database
  description: ''
  trigger:
  - platform: time
    at: 04:00:00
  condition: []
  action:
  - service: recorder.purge
    data:
      keep_days: 7
  mode: single
- id: '1641517010562'
  alias: Welcome Guests
  description: Control the entry lights when I’m home and the sun sets
  trigger:
  - platform: sun
    event: sunset
    offset: '0'
  condition:
  - condition: device
    device_id: b9be677b228a8396d688a589876b0bd1
    domain: device_tracker
    entity_id: device_tracker.red_fox
    type: is_home
  action:
  - scene: scene.welcome_guests
  mode: parallel
  max: 10
- id: '1641517261412'
  alias: Shoo Guests
  description: Thurman off the entry lights at night to save power
  trigger:
  - platform: time
    at: 02:00:00
  condition: []
  action:
  - type: turn_off
    device_id: 4e53a2915a2d7c3849f6dedc272883d8
    entity_id: light.front_porch
    domain: light
  - type: turn_off
    device_id: bf24fbce6a5fffc8507105615905aa7f
    entity_id: light.back_door
    domain: light
  mode: parallel
  max: 10
- id: '1641859068691'
  alias: Garage Security Alert
  description: ''
  trigger:
  - platform: device
    device_id: 59ffbcbe93e71327aa47111c5e8c6e4e
    domain: cover
    entity_id: cover.meross_garage_door
    type: opening
  condition:
  - condition: device
    device_id: b9be677b228a8396d688a589876b0bd1
    domain: device_tracker
    entity_id: device_tracker.red_fox
    type: is_not_home
  action:
  - device_id: b9be677b228a8396d688a589876b0bd1
    domain: mobile_app
    type: notify
    message: 'Alert: Garage Door Has Been Opened'
    title: 🚨 Garage Alert 🚨
  mode: single
- id: '1642458921261'
  alias: Secure the Home
  description: ''
  trigger:
  - platform: device
    device_id: b9be677b228a8396d688a589876b0bd1
    domain: device_tracker
    entity_id: device_tracker.red_fox
    type: leaves
    zone: zone.home
  condition: []
  action:
  - scene: scene.away_from_home
  - service: notify.notify
    data:
      message: Away from Home has run
  mode: single
- id: '1643035187105'
  alias: Control Basement Lights
  description: ''
  use_blueprint:
    path: vanstinator/zha-philips-hue-dimmer-switch-rwl020-rwl021.yaml
    input:
      remote: e591ad51e745970a7aaac1d24a8f25da
      light:
        area_id: basement
      force_brightness: true
- id: '1645557753855'
  alias: Welcome Home
  description: ''
  trigger:
  - platform: device
    device_id: b9be677b228a8396d688a589876b0bd1
    domain: device_tracker
    entity_id: device_tracker.red_fox
    type: enters
    zone: zone.home
  condition: []
  action:
  - service: alarm_control_panel.alarm_disarm
    data: {}
    target:
      entity_id:
      - alarm_control_panel.aarlo_base_station
      - alarm_control_panel.abode_alarm
  mode: single
- id: '1645558156781'
  alias: Lock the Doors
  description: 'This automation will figure out which door is shut and lock the appropriate
    door. '
  trigger:
  - type: not_opened
    platform: device
    device_id: 5fcc38e207ff017d468d01b9c85f7d03
    entity_id: binary_sensor.back_door
    domain: binary_sensor
  - type: not_opened
    platform: device
    device_id: 0f383bd14f58071a1596cd4d15313143
    entity_id: binary_sensor.front_door
    domain: binary_sensor
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - device_id: cdfa407440bf7e863d8043660c488d7d
    domain: lock
    entity_id: lock.back_door
    type: lock
  - device_id: 67aeebcc0ec0ba94e1d8860b04902e3a
    domain: lock
    entity_id: lock.front_door_lock
    type: lock
  mode: single
- id: '1645559073968'
  alias: Mount Media on HA Start
  description: Add things to the media folder so I can actually unleash some fun automations
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: shell_command.mount_music
  - service: shell_command.mount_video
  - service: shell_command.mount_plex
  - service: shell_command.mount_media
  mode: single
- id: '1645628585522'
  alias: Dining Room Occupancy Cleared
  description: ''
  trigger:
  - type: not_occupied
    platform: device
    device_id: 226ea18421499cba0c138db444b3b13a
    entity_id: binary_sensor.dining_room_occupancy_nest
    domain: binary_sensor
  condition:
  - type: is_not_occupied
    condition: device
    device_id: 1ff6fcee8d636f6fa35af30a5991ef89
    entity_id: binary_sensor.dining_room_occupancy
    domain: binary_sensor
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.dining_room_dimmer
  mode: single
